modLoader="javafml"
loaderVersion="[35,)"
license="MIT"
issueTrackerURL="http://github.com/Johan2403/ExampleMod/issues"
[[mods]]
modId="examplemod"
version="${version}"
displayName="Example Mod"
updateJSONURL="https://gist.githubusercontent.com/Johan2403/e1f6ccac945ab8b1c6a052703e239fca/raw/ExampleModUpdate.json"
displayURL="http://github.com/Johan2403/ExampleMod"
logoFile="examplemod.png"
credits="Mom and Dad."
authors="Johan24"
description='''
This is an Example Mod made by Johan24 for Minecraft 1.16.4 Forge.
The intent of this mod is to give valid examples of how to do some basic stuff using Forge API.

This Mod is Licensed under the MIT License.
'''
[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"
