@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package johan24.forge.examplemod.block;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;