@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package johan24.mods.examplemod.tileentity;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;