@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package mods.johan24.examplemod.tileentity;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;