@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package johan24.forge.examplemod.tileentity;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;